-- public スキーマに users テーブルを作成
CREATE TABLE public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- usersテーブルにカラムを追加
ALTER TABLE public.users
ADD COLUMN reset_password_token VARCHAR(255),
ADD COLUMN reset_password_token_expiry TIMESTAMP;

-- データベースレベルでの制約: SupabaseのusersテーブルにUNIQUE制約を追加して、物理的に重複を許さないようにします。これが最も強力です。
-- アプリケーションレベルでの事前チェック: 新規登録時に、入力されたメールアドレスが既に存在しないかをチェックし、存在した場合はエラーメッセージを画面に表示します。これにより、ユーザー体験が向上します。
ALTER TABLE public.users
ADD CONSTRAINT users_email_key UNIQUE (email);

-- NOT NULL制約なしで、デフォルト値付きのカラムを追加する
ALTER TABLE public.logs
ADD COLUMN is_public BOOLEAN DEFAULT false;

-- カラムにNOT NULL制約を追加する
ALTER TABLE public.logs
ALTER COLUMN is_public SET NOT NULL;